<?php

/**
 * ZakaznikTarifTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ZakaznikTarifTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ZakaznikTarifTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ZakaznikTarif');
    }
}