<?php

/**
 * APAntenaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class APAntenaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object APAntenaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('APAntena');
    }
}