<?php

/**
 * APAntennaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class APAntennaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object APAntennaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('APAntenna');
    }
}