<?php

/**
 * APHwTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class APHwTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object APHwTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('APHw');
    }
}