<?php

/**
 * APNetworkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class APNetworkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object APNetworkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('APNetwork');
    }
}