<?php

/**
 * APPortTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class APPortTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object APPortTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('APPort');
    }
}