<?php

/**
 * APTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class APTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object APTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AP');
    }
}