<?php

/**
 * AdresarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdresarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdresarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Adresar');
    }
}