<?php

/**
 * AdresarAdresaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdresarAdresaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdresarAdresaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdresarAdresa');
    }
}