<?php

/**
 * APHwIfTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class APHwIfTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object APHwIfTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('APHwIf');
    }
}