<?php

/**
 * APIPTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class APIPTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object APIPTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('APIP');
    }
}