<?php

/**
 * APParamsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class APParamsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object APParamsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('APParams');
    }
}