<?php

/**
 * APPokrytiSubnetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class APPokrytiSubnetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object APPokrytiSubnetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('APPokrytiSubnet');
    }
}