<?php

/**
 * APPortVlanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class APPortVlanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object APPortVlanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('APPortVlan');
    }
}