<?php

/**
 * APRouteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class APRouteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object APRouteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('APRoute');
    }
}