<?php

/**
 * APServiceOSListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class APServiceOSListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object APServiceOSListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('APServiceOSList');
    }
}