<?php

/**
 * APServiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class APServiceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object APServiceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('APService');
    }
}