<?php

/**
 * APServiceListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class APServiceListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object APServiceListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('APServiceList');
    }
}