<?php

/**
 * APSwIfTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class APSwIfTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object APSwIfTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('APSwIf');
    }
}