<?php

/**
 * TarifTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TarifTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TarifTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tarif');
    }
}