<?php

/**
 * ZakaznikNeaktivniTarifTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ZakaznikNeaktivniTarifTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ZakaznikNeaktivniTarifTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ZakaznikNeaktivniTarif');
    }
}