<?php

/**
 * ZakaznikNeaktivniTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ZakaznikNeaktivniTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ZakaznikNeaktivniTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ZakaznikNeaktivni');
    }
}