{block #content}

<h1 n:block="title">Customer list</h1>

<p><a href="{link add, 'customer'}">Add new customer record</a></p>

<table class="grid">
<tr>
	<th>Internal ID</th>
	<th>Contract number</th>
	<th>&nbsp;</th>
</tr>
<tr n:foreach="$customers as $customer">
	<td>{$customer->custId}</td>
	<td><a href="{link detail, $customer->custId}">{$customer->contractNumber}</a></td>
	<td>
		<a href="{link edit, $customer->custId}">Edit</a>
		<a href="{link delete, $customer->custId}">Delete</a>
	</td>
</tr>
</table>
