{block #content}

<h1 n:block="title">Customer list</h1>

<ul>
  <li><a href="{link add, 'customer'}">Add new customer record</a></li>
  <li><a href="{link Contract:add}">Add new contract</a></li>
</ul>


<table class="grid">
<tr>
	<th>Internal ID</th>
	<th>Contract number</th>
	<th>&nbsp;</th>
</tr>
<tr n:foreach="$customers as $customer">
	<td>{$customer->custId}</td>
	<td><a href="{link detail, $customer->custId}">{$customer->contractNumber}</a></td>
	<td>
		<a href="{link edit, 'customer', $customer->custId}">Edit</a>
		<a href="{link delete, 'customer', $customer->custId}">Delete</a>
	</td>
</tr>
</table>
