<?php
namespace Thrift\tutorial;
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
include_once $GLOBALS['THRIFT_ROOT'].'/packages/tutorial/tutorial_types.php';

$GLOBALS['tutorial_CONSTANTS'] = array();

$GLOBALS['tutorial_CONSTANTS']['INT32CONSTANT'] = 9853;

$GLOBALS['tutorial_CONSTANTS']['MAPCONSTANT'] = array(
  "hello" => "world",
  "goodnight" => "moon",
);

?>
