<?php
namespace Thrift\Nagios;
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
include_once $GLOBALS['THRIFT_ROOT'].'/Thrift.php';

include_once $GLOBALS['THRIFT_ROOT'].'/packages/nagios/nagios_types.php';

interface NagiosIf {
  public function updateConfiguration($conf);
  public function reloadConfig();
  public function start();
  public function stop();
  public function restart();
  public function getStatistics();
}

class NagiosClient implements \Thrift\Nagios\NagiosIf {
  protected $input_ = null;
  protected $output_ = null;

  protected $seqid_ = 0;

  public function __construct($input, $output=null) {
    $this->input_ = $input;
    $this->output_ = $output ? $output : $input;
  }

  public function updateConfiguration($conf)
  {
    $this->send_updateConfiguration($conf);
  }

  public function send_updateConfiguration($conf)
  {
    $args = new \Thrift\Nagios\Nagios_updateConfiguration_args();
    $args->conf = $conf;
    $bin_accel = ($this->output_ instanceof \TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'updateConfiguration', \TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('updateConfiguration', \TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }
  public function reloadConfig()
  {
    $this->send_reloadConfig();
  }

  public function send_reloadConfig()
  {
    $args = new \Thrift\Nagios\Nagios_reloadConfig_args();
    $bin_accel = ($this->output_ instanceof \TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'reloadConfig', \TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('reloadConfig', \TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }
  public function start()
  {
    $this->send_start();
  }

  public function send_start()
  {
    $args = new \Thrift\Nagios\Nagios_start_args();
    $bin_accel = ($this->output_ instanceof \TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'start', \TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('start', \TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }
  public function stop()
  {
    $this->send_stop();
  }

  public function send_stop()
  {
    $args = new \Thrift\Nagios\Nagios_stop_args();
    $bin_accel = ($this->output_ instanceof \TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'stop', \TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('stop', \TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }
  public function restart()
  {
    $this->send_restart();
  }

  public function send_restart()
  {
    $args = new \Thrift\Nagios\Nagios_restart_args();
    $bin_accel = ($this->output_ instanceof \TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'restart', \TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('restart', \TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }
  public function getStatistics()
  {
    $this->send_getStatistics();
    return $this->recv_getStatistics();
  }

  public function send_getStatistics()
  {
    $args = new \Thrift\Nagios\Nagios_getStatistics_args();
    $bin_accel = ($this->output_ instanceof \TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'getStatistics', \TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('getStatistics', \TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }

  public function recv_getStatistics()
  {
    $bin_accel = ($this->input_ instanceof \TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, '\Thrift\Nagios\Nagios_getStatistics_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $this->input_->readMessageBegin($fname, $mtype, $rseqid);
      if ($mtype == \TMessageType::EXCEPTION) {
        $x = new \TApplicationException();
        $x->read($this->input_);
        $this->input_->readMessageEnd();
        throw $x;
      }
      $result = new \Thrift\Nagios\Nagios_getStatistics_result();
      $result->read($this->input_);
      $this->input_->readMessageEnd();
    }
    if ($result->success !== null) {
      return $result->success;
    }
    throw new \Exception("getStatistics failed: unknown result");
  }

}

// HELPER FUNCTIONS AND STRUCTURES

class Nagios_updateConfiguration_args extends \TBase {
  static $_TSPEC;

  public $conf = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'conf',
          'name' => '\Thrift\Nagios\Configuration',
          'type' => \TType::STRUCT,
          'class' => '\Thrift\Nagios\Configuration',
          ),
        );
    }
    if (is_array($vals)) {
      parent::__construct(self::$_TSPEC, $vals);
    }
  }

  public function getName() {
    return 'Nagios_updateConfiguration_args';
  }

  public function read($input)
  {
    return $this->_read('Nagios_updateConfiguration_args', self::$_TSPEC, $input);
  }
  public function write($output) {
    return $this->_write('Nagios_updateConfiguration_args', self::$_TSPEC, $output);
  }
}

class Nagios_reloadConfig_args extends \TBase {
  static $_TSPEC;


  public function __construct() {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        );
    }
  }

  public function getName() {
    return 'Nagios_reloadConfig_args';
  }

  public function read($input)
  {
    return $this->_read('Nagios_reloadConfig_args', self::$_TSPEC, $input);
  }
  public function write($output) {
    return $this->_write('Nagios_reloadConfig_args', self::$_TSPEC, $output);
  }
}

class Nagios_start_args extends \TBase {
  static $_TSPEC;


  public function __construct() {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        );
    }
  }

  public function getName() {
    return 'Nagios_start_args';
  }

  public function read($input)
  {
    return $this->_read('Nagios_start_args', self::$_TSPEC, $input);
  }
  public function write($output) {
    return $this->_write('Nagios_start_args', self::$_TSPEC, $output);
  }
}

class Nagios_stop_args extends \TBase {
  static $_TSPEC;


  public function __construct() {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        );
    }
  }

  public function getName() {
    return 'Nagios_stop_args';
  }

  public function read($input)
  {
    return $this->_read('Nagios_stop_args', self::$_TSPEC, $input);
  }
  public function write($output) {
    return $this->_write('Nagios_stop_args', self::$_TSPEC, $output);
  }
}

class Nagios_restart_args extends \TBase {
  static $_TSPEC;


  public function __construct() {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        );
    }
  }

  public function getName() {
    return 'Nagios_restart_args';
  }

  public function read($input)
  {
    return $this->_read('Nagios_restart_args', self::$_TSPEC, $input);
  }
  public function write($output) {
    return $this->_write('Nagios_restart_args', self::$_TSPEC, $output);
  }
}

class Nagios_getStatistics_args extends \TBase {
  static $_TSPEC;


  public function __construct() {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        );
    }
  }

  public function getName() {
    return 'Nagios_getStatistics_args';
  }

  public function read($input)
  {
    return $this->_read('Nagios_getStatistics_args', self::$_TSPEC, $input);
  }
  public function write($output) {
    return $this->_write('Nagios_getStatistics_args', self::$_TSPEC, $output);
  }
}

class Nagios_getStatistics_result extends \TBase {
  static $_TSPEC;

  public $success = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        0 => array(
          'var' => 'success',
          'name' => 'string',
          'type' => \TType::STRING,
          ),
        );
    }
    if (is_array($vals)) {
      parent::__construct(self::$_TSPEC, $vals);
    }
  }

  public function getName() {
    return 'Nagios_getStatistics_result';
  }

  public function read($input)
  {
    return $this->_read('Nagios_getStatistics_result', self::$_TSPEC, $input);
  }
  public function write($output) {
    return $this->_write('Nagios_getStatistics_result', self::$_TSPEC, $output);
  }
}

class NagiosProcessor {
  protected $handler_ = null;
  public function __construct($handler) {
    $this->handler_ = $handler;
  }

  public function process($input, $output) {
    $rseqid = 0;
    $fname = null;
    $mtype = 0;

    $input->readMessageBegin($fname, $mtype, $rseqid);
    $methodname = 'process_'.$fname;
    if (!method_exists($this, $methodname)) {
      $input->skip(\TType::STRUCT);
      $input->readMessageEnd();
      $x = new \TApplicationException('Function '.$fname.' not implemented.', \TApplicationException::UNKNOWN_METHOD);
      $output->writeMessageBegin($fname, \TMessageType::EXCEPTION, $rseqid);
      $x->write($output);
      $output->writeMessageEnd();
      $output->getTransport()->flush();
      return;
    }
    $this->$methodname($rseqid, $input, $output);
    return true;
  }

  protected function process_updateConfiguration($seqid, $input, $output) {
    $args = new \Thrift\Nagios\Nagios_updateConfiguration_args();
    $args->read($input);
    $input->readMessageEnd();
    $this->handler_->updateConfiguration($args->conf);
    return;
  }
  protected function process_reloadConfig($seqid, $input, $output) {
    $args = new \Thrift\Nagios\Nagios_reloadConfig_args();
    $args->read($input);
    $input->readMessageEnd();
    $this->handler_->reloadConfig();
    return;
  }
  protected function process_start($seqid, $input, $output) {
    $args = new \Thrift\Nagios\Nagios_start_args();
    $args->read($input);
    $input->readMessageEnd();
    $this->handler_->start();
    return;
  }
  protected function process_stop($seqid, $input, $output) {
    $args = new \Thrift\Nagios\Nagios_stop_args();
    $args->read($input);
    $input->readMessageEnd();
    $this->handler_->stop();
    return;
  }
  protected function process_restart($seqid, $input, $output) {
    $args = new \Thrift\Nagios\Nagios_restart_args();
    $args->read($input);
    $input->readMessageEnd();
    $this->handler_->restart();
    return;
  }
  protected function process_getStatistics($seqid, $input, $output) {
    $args = new \Thrift\Nagios\Nagios_getStatistics_args();
    $args->read($input);
    $input->readMessageEnd();
    $result = new \Thrift\Nagios\Nagios_getStatistics_result();
    $result->success = $this->handler_->getStatistics();
    $bin_accel = ($output instanceof \TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($output, 'getStatistics', \TMessageType::REPLY, $result, $seqid, $output->isStrictWrite());
    }
    else
    {
      $output->writeMessageBegin('getStatistics', \TMessageType::REPLY, $seqid);
      $result->write($output);
      $output->getTransport()->flush();
    }
  }
}
?>
