<?php

/**
 * AdresarZalohovyUcetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdresarZalohovyUcetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdresarZalohovyUcetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdresarZalohovyUcet');
    }
}