<?php

/**
 * AdresarKontaktTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdresarKontaktTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdresarKontaktTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdresarKontakt');
    }
}