<?php

/**
 * TarifRychlostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TarifRychlostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TarifRychlostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TarifRychlost');
    }
}