<?php

/**
 * TarifFlagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TarifFlagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TarifFlagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TarifFlag');
    }
}