{block content}

<h1 n:block="title">Welcome to ISP manager</h1>

<div>
  <h3>Useful links</h3>
  <ul>
    <li><a href="{link :ap:dashboard:default}">Access point module</a></li>
    <li><a href="{link :customer:dashboard:default}">Customer module</a></li>
    <li><a href="{link :payment:dashboard:default}">Payments module</a></li>
    <li><a href="{link :common:tarif:default}">tariffs</a></li>
    <li><a href="{link :Monitoring:Nagios:default}">Nagios</a></li>
    <li><a href="{link :Base:Layout:default}">Choose layout</a></li>
  </ul>
</div>
