{block content}

<div id="header">
	<h1>It works!</h1>

	<h2>Welcome to ISP manager</h2>
</div>

<div>
  <h3>Useful links</h3>
  <ul>
    <li><a href="{link :ap:dashboard:default}">Access point module</a></li>
    <li><a href="{link :customer:dashboard:default}">Customer module</a></li>
    <li><a href="{link :payment:dashboard:default}">Payments module</a></li>
    <li><a href="{link :common:tarif:default}">tariffs</a></li>
  </ul>
</div>

<a href="{link :Base:Sign:out}">Sign out</a>