<?php

/**
 * PlatbaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlatbaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlatbaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Platba');
    }
}