{block #content}

<h1 n:block="title">UI tests</h1>

<form>
  <table>
    <tr><th>Date:</th><td><input type="text" name="published" format="date" /></td></tr>
    <tr><th>Time:</th><td><input type="text" name="time" format="time" /></td></tr>
    <tr><th>Datetime:</th><td><input type="text" name="time2" format="datetime" /></td></tr>

    <tr><th>Color:</th><td><input type="text" name="color" format="color" /></td></tr>

    <tr><th>Number:</th><td><input type="text" name="x" format="int" /></td></tr>
    <tr><th>Float:</th><td><input type="text" name="t" format="float" /></td></tr>
    <tr><th>Currency:</th><td><input type="text" name="kc" format="currency" /></td></tr>

    <tr><th>IP:</th><td><input type="text" name="a" format="ip" /></td></tr>
    <tr><th>Netmask:</th><td><input type="text" name="b" format="netmask" /></td></tr>
    <tr><th>MAC:</th><td><input type="text" name="c" format="mac" /></td></tr>

  </table>
  


</form>