{block #content}

<h1 n:block="title">UI tests</h1>

<form>
  <table>
    <tr>
      <th>Date:</th>
      <td><input type="text" name="published" format="date" /></td>
    </tr>

    <tr>
      <th>Color</th>
      <td><input type="text" name="background" format="color" /></td>
    </tr>

    <tr>
      <th>Number</th>
      <td><input type="text" name="background" format="int" /></td>
    </tr>

    <tr>
      <th>IP</th>
      <td><input type="text" name="background" format="ip" /></td>
    </tr>

    <tr>
      <th>Netmask</th>
      <td><input type="text" name="background" format="netmask" /></td>
    </tr>


  </table>
  


</form>