#!/usr/bin/env php
<?php

define('APP_DIR', __DIR__ . '/../app');
define('LIBS_DIR', __DIR__ . '/../libs');

require __DIR__.'/../app/bootstrap-common.php';
$cli = new Doctrine_Cli(Nette\Environment::getVariable('doctrine_config'));
$cli->run($_SERVER['argv']);

