<?php
namespace Thrift;
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
include_once $GLOBALS['THRIFT_ROOT'].'/Thrift.php';


class SharedStruct extends \TBase {
  static $_TSPEC;

  public $key = null;
  public $value = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'key',
          'name' => 'i32',
          'type' => \TType::I32,
          ),
        2 => array(
          'var' => 'value',
          'name' => 'string',
          'type' => \TType::STRING,
          ),
        );
    }
    if (is_array($vals)) {
      parent::__construct(self::$_TSPEC, $vals);
    }
  }

  public function getName() {
    return 'SharedStruct';
  }

  public function read($input)
  {
    return $this->_read('SharedStruct', self::$_TSPEC, $input);
  }
  public function write($output) {
    return $this->_write('SharedStruct', self::$_TSPEC, $output);
  }
}

?>
