<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

	<meta name="description" content="iManaJUZment login page">
	<meta name="robots" content="{$robots}" n:ifset="$robots">

	<title>ISP manager | {block #title|striptags}Welcome{/block}</title>

	<link rel="stylesheet" media="screen,projection,tv" href="{$basePath}/css/screen.css" type="text/css">
	<link rel="stylesheet" media="print" href="{$basePath}/css/print.css" type="text/css">
  <link rel="stylesheet" href="{$basePath}/css/isp.css" type="text/css">
	<link rel="shortcut icon" href="{$basePath}/favicon.ico" type="image/x-icon">
  <script type="text/javascript" src="{$basePath}/js/jquery.js"></script>
  <script type="text/javascript" src="{$basePath}/js/jquery.nette.js"></script>
</head>

<body>
  <h1>Welcome to iManaJUZment system</h1>

	{foreach $flashes as $flash}<div class="flash {$flash->type}">{$flash->message}</div>{/foreach}

	{include #content}
</body>
</html>
