<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
  <title>iManaJUZment &ndash; Browser compatibility check</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=8" />
  <link rel="stylesheet" type="text/css" href="{$basePath}/css/browser-check.css" />
</head>
<body>
  <div id="page">
    <div id="pageInner">
      <div id="panel">
        <h1>iManaJUZment &ndash; Browser compatibility check</h1>
        <div id="content">
          <h2>To use this application in Internet Explorer, you have to install <a href="http://www.google.com/chromeframe">Google Chrome Frame</a> plugin</h2>
          <p><a href="http://www.google.com/chromeframe"><img src="{$basePath}/img/browser-check/install_button.gif" width="216" height="29" alt="Install Google Chrome Frame"></a></p>

          <p>Or use one of these supported browsers:</p>
          <table id="browsers" summary="" cellspacing="0">
          <tr>
            <td id="browserFirefox"><a href="http://www.mozilla.com/firefox/">Firefox 3.5</a></td>
            <td id="browserChrome"><a href="http://www.google.com/chrome">Google Chrome</a></td>
            <td id="browserSafari"><a href="http://www.apple.com/safari/">Safari 4</a></td>
          </tr>
          </table>

          <p>If you want to continue at your own peril, <a href="{link in, useIE => 1}">go ahead</a>.</p>
        </div>
      </div>
    </div>
  </div>
</body>
</html>