{extends '@layout.phtml'}
{var $robots = noindex}

{block #content}

<h2 n:block="title">Sign in</h2>
<p>You have to sing in to access this application</p>

<fieldset>
  <legend>Sign in by password</legend>
  {control signInForm}
</fieldset>

<fieldset>
  <legend>Sign in using OpenID</legend>
  <p>
    <a href="{link signViaGoogle}">Sign using Google</a> |
    <a href="{link registerViaGoogle}">Register using Google</a>
  </p>
</fieldset>




